services:
  caddy:
    image: caddy:latest
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - $PWD/data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
