services:
  grafana:
    image: 'grafana/grafana'
    restart: always

    depends_on:
      - caddy

    ports:
      - "3000:3000"

    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
    external: true
