services:
  graphite:
    image: 'graphiteapp/graphite-statsd'
    restart: always

    depends_on:
      - grafana

    environment:
      COLLECTD_DOCKER_APP: graphite

    ports:
      - "8000:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  container_metrics:
    image: bobrik/collectd-docker
    restart: always

    depends_on:
      - graphite

    environment:
      COLLECTD_INTERVAL: 5
      GRAPHITE_HOST: graphite
      COLLECTD_HOST: xithriuscloud

    labels:
      - collectd_docker_app

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
