services:
  prometheus:
    image: 'prom/prometheus'
    user: root
    restart: always

    depends_on:
      - grafana

    environment:
      COLLECTD_DOCKER_APP: prometheus

    ports:
      - "9090:9090"

    volumes:
      - $PWD/data/prometheus:/etc/prometheus/:rw
      - $PWD/data/prometheus/prometheus_data:/prometheus:rw

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
