global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets: ["xithriuscloud_prometheus_1:9090"]

- job_name: "cloudflare"
  static_configs:
  - targets: ["xithriuscloud_cloudflare_1:8080"]
