services:
  postgres:
    image: postgres:14-alpine
    restart: always

    environment:
      COLLECTD_DOCKER_APP: graphite
      POSTGRES_DB: site
      POSTGRES_PASSWORD: site
      POSTGRES_USER: site

    ports:
      - "7777:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U site"]
      interval: 2s
      timeout: 1s
      retries: 5

    volumes:
      - $PWD/services/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
