name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix: { dir: ["site"] }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: bun install

      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: bun ci
